<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ModName>Template</ModName>
        <AssemblyName>$(ModName)</AssemblyName>
        <RootNamespace>$(ModName)</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
      <Folder Include="Assets\" />
      <Folder Include="Localization\" />
    </ItemGroup>

    <!-- Import Subnautica VS properties - paths etc. -->
    <Import Project="$(SolutionDir)Subnautica.VS.props" />

    <!-- Import Game/Unity DLL references -->
    <Import Project="$(SolutionDir)Subnautica.VS.References.props" />
</Project>