<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <BaseOutputPath>$(SolutionDir)Build\</BaseOutputPath>
        <BaseIntermediateOutputPath>$(SolutionDir)Objects\</BaseIntermediateOutputPath>
        <MSBuildProjectExtensionsPath>$(SolutionDir)Objects\</MSBuildProjectExtensionsPath>
    </PropertyGroup>
</Project>