<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ModName>SubnauticaPlus</ModName>
        <AssemblyName>$(ModName)</AssemblyName>
        <RootNamespace>$(ModName)</RootNamespace>
    </PropertyGroup>

    <!-- Import Subnautica VS properties - paths etc. -->
    <Import Project="$(SolutionDir)Subnautica.VS.props" />

    <!-- Import Game/Unity DLL references -->
    <Import Project="$(SolutionDir)Subnautica.VS.References.props" />
	
    <ItemGroup>
      <ProjectReference Include="$(SolutionDir)Source\SubnauticaLibrary\SubnauticaLibrary.csproj" />
    </ItemGroup>
</Project>